In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import pylab as pl




%pylab inline

Populating the interactive namespace from numpy and matplotlib

/Users/baileygriswold/anaconda3/lib/python3.6/site-packages/IPython/core/magics/pylab.py:160: UserWarning: pylab import has clobbered these variables: ['plt']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"

In [2]:
df = pd.read_csv('./schma_data/schma19962016.csv')
df.head()

/Users/baileygriswold/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (124,125,126,148,149,150,183,220,221,222,226,227,230,231,232,234,235,247) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,DBN,SCHNAM,YEAR,SCHLEV,SCHLEV5,SCHS219962016,XDBN,XDBN_FLAG,ENRNUMPRK,ENRNUMKID,...,BNLONG_YRFIRST,BNLONG_YRLAST,BNLONG_TOTALYRS,BNLONG_PHASEDOUT19962016,BNLONG_PHASEDIN19962016,BNLONG_CONTOPERATE19962016,CBO,HSJHS,HSSCHSAMP2,SPECHS
0,00M801,HUNTER SCHOOL,1996,NaN,NaN,NaN,00M801,0,16,48,...,1996,1998,3.0,1,0,0,0,NaN,6,0
1,00M802,HUNTER SCHOOL,1996,NaN,NaN,NaN,00M802,0,0,0,...,1996,1998,3.0,1,0,0,0,1.0,6,0
2,00M803,HUNTER SCHOOL,1996,NaN,NaN,NaN,00M803,0,0,0,...,1996,1998,3.0,1,0,0,0,0.0,6,0
3,01M015,ROBERTO CLEMENTE,1996,NaN,NaN,NaN,01M015,0,0,36,...,1996,2016,21.0,0,0,0,0,NaN,6,0
4,01M019,ASHER LEVY,1996,NaN,NaN,NaN,01M019,0,33,82,...,1996,2016,21.0,0,0,0,0,NaN,6,0

In [3]:
df.shape

(30345, 270)

In [4]:
df['BNLONG_CONTOPERATE19962016'].value_counts(dropna=False)

0    30345
Name: BNLONG_CONTOPERATE19962016, dtype: int64

In [5]:
#highest year for BN number -- when a school was closed?
df['BNLONG_YRLAST'].value_counts(dropna=False)

2016    26658
2015      965
2014      436
2007      255
2011      239
2006      230
2010      195
2009      169
2005      167
2008      160
2004      150
2012      130
2002      124
2001      115
2013      114
2003       94
2000       51
1998       35
1999       32
1997       18
1996        8
Name: BNLONG_YRLAST, dtype: int64

Which schools have closed down?

Renewal schools:
PS 050 Vito Marcantonio (04M050) 2017
Coalition School for Social Change (04M409) 2017
High School for Health Careers and Sciences (06M468) 2017
New Explorers High School (07X547) 2017
Urban Science Academy (09X325) 2017
PS 92 Bronx School (12X092) 2017
Brooklyn Collegiate: A College Board School (23K493) 2017
PS/MS 42 R. Vernam (27Q042) 2017
MS 53 Brian Piccolo (27Q053) 2017
Holcombe L. Rucker School of Community (08X332) 2017
Entrada Academy (12X384)
Middle School of Marketing and Legal Studies (18K598)
Gregory Jocko Jackson School (23K284) (just middle school years)
P.S. 306 Ethan Allen and P.S. 165 Ida Posner. (truncating middle schools)
Paul Robeson High School

Hard to find out which are schools that have been shut down!

Features notes
- academic expectations (average, and compared to city and peer horizon scores) - could be a good measure of school performance? (comparing expectation to peer horizon)
- attendance -- have some grades reporting over 100% attendnace?

In [6]:
df[df.HSSCHSAMP2 == 4]

,DBN,SCHNAM,YEAR,SCHLEV,SCHLEV5,SCHS219962016,XDBN,XDBN_FLAG,ENRNUMPRK,ENRNUMKID,...,BNLONG_YRFIRST,BNLONG_YRLAST,BNLONG_TOTALYRS,BNLONG_PHASEDOUT19962016,BNLONG_PHASEDIN19962016,BNLONG_CONTOPERATE19962016,CBO,HSJHS,HSSCHSAMP2,SPECHS
1108,79K409,EAST NEW YORK FAMILY ACADEMY,1996,NaN,NaN,NaN,79K409,0,0,0,...,1996,2015,NaN,1,0,0,0,0.0,4,0
1109,79K510,AUX SERVICES (BROOKLYN),1996,NaN,NaN,NaN,79K510,0,0,0,...,1996,2015,NaN,1,0,0,0,NaN,4,0
1110,79K511,BEDFORD STUYVESANT OUTREACH,1996,NaN,NaN,NaN,79K511,0,0,0,...,1996,2003,8.0,1,0,0,0,0.0,4,0
1111,79K512,BUSHWICK OUTREACH,1996,NaN,NaN,NaN,79K512,0,0,0,...,1996,2004,9.0,1,0,0,0,0.0,4,0
1112,79K565,HIGH SCHOOL REDIRECTION,1996,NaN,NaN,NaN,79K565,0,0,0,...,1996,2004,9.0,1,0,0,0,0.0,4,0
1113,79K573,BROOKLYN BOROUGH ACADEMY,1996,NaN,NaN,NaN,79K573,0,0,0,...,1996,2003,8.0,1,0,0,0,0.0,4,0
1114,79K580,BROOKLYN LITERACY CENTER,1996,NaN,NaN,NaN,79K580,0,0,0,...,1996,2003,8.0,1,0,0,0,0.0,4,0
1115,79K591,BROOKLYN OFF-SITE ED SERVICES,1996,NaN,NaN,NaN,79K591,0,0,0,...,1996,2005,10.0,1,0,0,0,0.0,4,0
1116,79K665,NYC VOCATIONAL TRAINING CENTER,1996,NaN,NaN,NaN,79K665,0,0,0,...,1996,2007,12.0,1,0,0,0,0.0,4,0
1117,79K931,TEEN AID HIGH SCHOOL,1996,NaN,NaN,NaN,79K931,0,0,0,...,1996,2002,7.0,1,0,0,0,0.0,4,0
1118,79K932,COMMUNITY SCHL FOR CONT ED,1996,NaN,NaN,NaN,79K932,0,0,0,...,1996,2007,12.0,1,0,0,0,0.0,4,0
1119,79M469,CHOIR ACADEMY OF HARLEM,1996,NaN,NaN,NaN,79M469,0,0,0,...,1996,2015,NaN,1,0,0,0,0.0,4,0
1120,79M479,BEACON SCHOOL,1996,NaN,NaN,NaN,79M479,0,0,0,...,1996,2016,21.0,0,0,0,0,0.0,4,0
1121,79M500,UNITY HIGH SCHOOL,1996,NaN,NaN,NaN,79M500,0,0,0,...,1996,2016,21.0,0,0,0,0,0.0,4,0
1122,79M501,WEST MANHATTAN OUTREACH,1996,NaN,NaN,NaN,79M501,0,0,0,...,1996,2015,NaN,1,0,0,0,0.0,4,0
1123,79M502,LOWER MANHATTAN OUTREACH,1996,NaN,NaN,NaN,79M502,0,0,0,...,1996,2004,9.0,1,0,0,0,0.0,4,0
1124,79M510,AUX SERVICES (MANHATTAN),1996,NaN,NaN,NaN,79M510,0,0,0,...,1996,2007,12.0,1,0,0,0,NaN,4,0
1125,79M530,PROJECT BLEND,1996,NaN,NaN,NaN,79M530,0,0,0,...,1996,2004,9.0,1,0,0,0,0.0,4,0
1126,79M573,MANHATTAN BOROUGH ACADEMY,1996,NaN,NaN,NaN,79M573,0,0,0,...,1996,2003,8.0,1,0,0,0,0.0,4,0
1127,79M585,CAREER EDUCATION CENTER,1996,NaN,NaN,NaN,79M585,0,0,0,...,1996,2007,12.0,1,0,0,0,0.0,4,0
1128,79M590,PROJECT YOU,1996,NaN,NaN,NaN,79M590,0,0,0,...,1996,2002,7.0,1,0,0,0,0.0,4,0
1129,79M591,MANHATTAN OFF-SITE ED SERVICES,1996,NaN,NaN,NaN,79M591,0,0,0,...,1996,2005,10.0,1,0,0,0,0.0,4,0
1130,79M595,OUT-OF-CITY OFF-SITE ED SERVIC,1996,NaN,NaN,NaN,79M595,0,0,0,...,1996,2007,11.0,1,0,0,0,0.0,4,0
1131,79M690,SCHOOL FOR THE PHYSICAL CITY,1996,NaN,NaN,NaN,79M690,0,0,0,...,1996,2010,15.0,1,0,0,0,0.0,4,0
1132,79M695,URBAN PEACE ACADEMY,1996,NaN,NaN,NaN,79M695,0,0,0,...,1996,2010,15.0,1,0,0,0,0.0,4,0
1133,79M911,CENTER FOR CONTINUED EDUCATION,1996,NaN,NaN,NaN,79M911,0,0,0,...,1996,2007,11.0,1,0,0,0,0.0,4,0
1134,79Q510,AUX SERVICES (QUEENS),1996,NaN,NaN,NaN,79Q510,0,0,0,...,1996,2005,10.0,1,0,0,0,NaN,4,0
1135,79Q516,QUEENS OUTREACH ACADEMY,1996,NaN,NaN,NaN,79Q516,0,0,0,...,1996,2003,8.0,1,0,0,0,0.0,4,0
1136,79Q520,MIDDLE COLLEGE HS @ LAGUARDIA,1996,NaN,NaN,NaN,79Q520,0,0,0,...,1996,2016,19.0,0,0,0,0,0.0,4,0
1137,79Q530,INTERNATIONAL HS AT LA GUARDIA,1996,NaN,NaN,NaN,79Q530,0,0,0,...,1996,2016,19.0,0,0,0,0,0.0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28673,79X695,PASSAGES ACADEMY,2015,6.0,3.0,1.0,79X695,0,0,0,...,1999,2016,18.0,0,1,0,0,0.0,4,0
28792,02M473,WASHINGTON IRVING YABC,2016,7.0,4.0,1.0,02M473,0,0,0,...,2006,2016,11.0,0,1,0,0,NaN,4,0
28814,02M575,MANHATTAN COMPREHENSIVE NIGHT AND DAY HIGH SCHOOL,2016,8.0,4.0,1.0,02M575,0,0,0,...,1996,2016,21.0,0,0,0,0,0.0,4,0
28975,06M457,GEORGE WASHINGTON YABC,2016,7.0,4.0,1.0,06M457,0,0,0,...,2000,2016,13.0,0,1,0,0,NaN,4,0
29016,07X456,ALFRED E. SMITH CAMPUS YABC,2016,7.0,4.0,1.0,07X456,0,0,0,...,2007,2016,10.0,0,1,0,0,NaN,4,0
29075,08X408,HERBERT H. LEHMAN YABC,2016,7.0,4.0,1.0,08X408,0,0,0,...,2006,2016,11.0,0,1,0,0,NaN,4,0
29081,08X507,STEVENSON YABC,2016,7.0,4.0,1.0,08X507,0,0,0,...,2005,2016,12.0,0,1,0,0,NaN,4,0
29242,10X503,WALTON YABC,2016,7.0,4.0,1.0,10X503,0,0,0,...,2005,2016,12.0,0,1,0,0,NaN,4,0
29243,10X504,KENNEDY YABC,2016,7.0,4.0,1.0,10X504,0,0,0,...,2005,2016,12.0,0,1,0,0,NaN,4,0
29249,10X668,DEWITT CLINTON CAMPUS YABC,2016,7.0,4.0,1.0,10X668,0,0,0,...,2016,2016,1.0,0,1,0,0,NaN,4,0
29296,11X417,C COLUMBUS HS YABC,2016,7.0,4.0,1.0,11X417,0,0,0,...,2000,2016,17.0,0,1,0,0,NaN,4,0
29354,12X428,LEARNING TO WORK YABC AT MONROE ACADEMY,2016,7.0,4.0,1.0,12X428,0,0,0,...,2007,2016,10.0,0,1,0,0,NaN,4,0
29409,13K657,DOWNTOWN BROOKLYN YABC,2016,7.0,4.0,1.0,13K657,0,0,0,...,2010,2016,7.0,0,1,0,0,NaN,4,0
29454,14K923,AUTOMOTIVE HIGH SCHOOL YABC,2016,7.0,4.0,1.0,14K923,0,0,0,...,2008,2016,9.0,0,1,0,0,NaN,4,0
29534,16K959,BOYS AND GIRLS YABC,2016,7.0,4.0,1.0,16K959,0,0,0,...,2013,2016,4.0,0,1,0,0,NaN,4,0
29566,17K467,ERASMUS YABC,2016,7.0,4.0,1.0,17K467,0,0,0,...,2006,2016,11.0,0,1,0,0,NaN,4,0
29623,18K922,SOUTH SHORE EDUCATIONAL COMPLEX YABC,2016,7.0,4.0,1.0,18K922,0,0,0,...,2008,2016,9.0,0,1,0,0,NaN,4,0
29653,19K431,THOMAS JEFFERSON YABC,2016,7.0,4.0,1.0,19K431,0,0,0,...,2006,2016,11.0,0,1,0,0,NaN,4,0
29655,19K501,FRANKLIN K. LANE CAMPUS YABC,2016,7.0,4.0,1.0,19K501,0,0,0,...,2007,2016,10.0,0,1,0,0,NaN,4,0
29715,20K658,FRANKLIN DELANO ROOSEVELT YABC,2016,7.0,4.0,1.0,20K658,0,0,0,...,2009,2016,8.0,0,1,0,0,NaN,4,0
29753,21K411,ABRAHAM LINCOLN YABC,2016,7.0,4.0,1.0,21K411,0,0,0,...,2006,2016,11.0,0,1,0,0,NaN,4,0
29881,24Q457,H.S. ARTS & BUSINESS YABC,2016,7.0,4.0,1.0,24Q457,0,0,0,...,1999,2016,17.0,0,1,0,0,NaN,4,0
29932,25Q467,FLUSHING YABC,2016,7.0,4.0,1.0,25Q467,0,0,0,...,2006,2016,11.0,0,1,0,0,NaN,4,0
30031,27Q487,JOHN ADAMS YABC,2016,7.0,4.0,1.0,27Q487,0,0,0,...,2006,2016,11.0,0,1,0,0,NaN,4,0
30253,31R607,STATEN ISLAND YABC,2016,7.0,4.0,1.0,31R607,0,0,0,...,2002,2016,15.0,0,1,0,0,NaN,4,0
30340,79M973,RESTART ACADEMY,2016,6.0,3.0,1.0,79M973,0,0,0,...,2008,2016,9.0,0,1,0,0,0.0,4,0
30341,79M984,LYFE,2016,8.0,4.0,1.0,79M984,0,0,0,...,2015,2016,2.0,0,1,0,0,NaN,4,0
30342,79Q344,EAST RIVER ACADEMY,2016,6.0,3.0,1.0,79Q344,0,0,0,...,2011,2016,6.0,0,1,0,0,0.0,4,0
30343,79Q950,PATHWAYS TO GRADUATION,2016,5.0,4.0,1.0,79Q950,0,0,0,...,2008,2016,9.0,0,1,0,0,NaN,4,0
30344,79X695,PASSAGES ACADEMY,2016,6.0,3.0,1.0,79X695,0,0,0,...,1999,2016,18.0,0,1,0,0,0.0,4,0

In [7]:
df.LCGSTAT.value_counts(dropna=False)

OPEN      19689
NaN       10632
CLOSED       24
Name: LCGSTAT, dtype: int64

# Feature engineering

In [8]:
df_feats = pd.read_csv('./schma_data/schma features of interest.csv')
df_feats.head()

   Feat_Code          Feat_expl Notes
0  ATTPCTG01  School attendnace   NaN
1  ATTPCTG02  School attendnace   NaN
2  ATTPCTG03  School attendnace   NaN
3  ATTPCTG04  School attendnace   NaN
4  ATTPCTG05  School attendnace   NaN

In [9]:
codes = df_feats.Feat_Code

In [10]:
keep = df.columns[df.columns.isin(codes)]

In [11]:
keep = list(keep)

In [12]:
for x in ['DBN','SCHNAM','YEAR','BNLONG']:
    keep.append(x)

In [13]:
df.shape

(30345, 270)

In [14]:
df[keep].shape

(30345, 146)

In [15]:
#keeping only the features of interest
df = df[keep]

In [16]:
df_feats.sort_values(by='Notes').head(20)

,Feat_Code,Feat_expl,Notes
16,CCDENRNUMFRL,CCD: NUMBER STUDENTS ELIGIBLE FOR THE FREE OR ...,*need to normalize
17,CCDNUMFTE,CCD: CLASSROOM TEACHERS (FTE),*normalize by no stu
100,LCGSTAT,open close status,24 noted as closed
89,HPGPERDIP4AVG,HS PROG RPT: 4-YEAR DIPLOMA RATE (AVERAGE),CAN BE AN OUTCOME
88,HPGGENREGREMAVG,HS PROG RPT: COMPLETION RATE FOR REMAINING REG...,CAN BE AN OUTCOME
87,HPGGEN10CYR3AVG,HS PROG RPT: % 3RD YEAR GEN STUDENTS EARNING 1...,CAN BE AN OUTCOME
90,HPGPERDIP6AVG,HS PROG RPT: 6-YEAR RATE DIPLOMA (AVERAGE),CAN BE AN OUTCOME
85,HPGGEN10CYR1AVG,HS PROG RPT: % 1ST YEAR GEN STUDENTS EARNING 1...,CAN BE AN OUTCOME
84,HPGG08PROF,HS PROG RPT: AVERAGE 8TH GRADE PROFICIENCY,CAN BE AN OUTCOME
86,HPGGEN10CYR2AVG,HS PROG RPT: % 2ND YEAR GEN STUDENTS EARNING 1...,CAN BE AN OUTCOME
82,ENRNUMTOT,TOTAL enrollment,TOTAL enrollment
99,LCGSCHTYP,school type,drop everything that isn't a general academic ...
133,STCELAPCTL34G08,"ELA STATE TEST, NYC: PERCENT AT LEVEL THREE OR...","feature for clustering, but outcome for classi..."
128,STCELAPCTL34G03,"ELA STATE TEST, NYC: PERCENT AT LEVEL THREE OR...","feature for clustering, but outcome for classi..."
129,STCELAPCTL34G04,"ELA STATE TEST, NYC: PERCENT AT LEVEL THREE OR...","feature for clustering, but outcome for classi..."
130,STCELAPCTL34G05,"ELA STATE TEST, NYC: PERCENT AT LEVEL THREE OR...","feature for clustering, but outcome for classi..."
131,STCELAPCTL34G06,"ELA STATE TEST, NYC: PERCENT AT LEVEL THREE OR...","feature for clustering, but outcome for classi..."
132,STCELAPCTL34G07,"ELA STATE TEST, NYC: PERCENT AT LEVEL THREE OR...","feature for clustering, but outcome for classi..."
134,STCELAPCTL34TOT,"ELA STATE TEST, NYC: PERCENT AT LEVEL THREE OR...","feature for clustering, but outcome for classi..."
0,ATTPCTG01,School attendnace,NaN

In [17]:
df['CCDNUMFTE_normd'] = (df['CCDNUMFTE'] / df['ENRNUMTOT'])

In [18]:
df['CCDENRNUMFRL_normd'] = (df['CCDENRNUMFRL'] / df['ENRNUMTOT'])

In [19]:
df['LCGSCHTYP'].value_counts(dropna=False).index

Index([ 'GENERAL ACADEMIC',                 nan,                 'S',
       'SPECIAL EDUCATION',   'TRANSFER SCHOOL',       'ALTERNATIVE',
        'CAREER TECHNICAL',       'HOME SCHOOL',              'YABC',
       'SUSPENSION CENTER',                'FC',                 'P',
          'NOT APPLICABLE',                 'I',       'BUDGET ONLY',
                   'ADULT'],
      dtype='object')

YABC = young adult burrough center\

In [20]:
len(df[df['LCGSCHTYP'].isin(['HOME SCHOOL','YABC',
       'SUSPENSION CENTER', 'FC',  'P',
             'BUDGET ONLY', 'NOT APPLICABLE','I',
                   'ADULT'])])

78

In [21]:
#dropping alt school types
df = df[~df['LCGSCHTYP'].isin(['HOME SCHOOL','YABC',
       'SUSPENSION CENTER', 'FC',  'P',
             'BUDGET ONLY', 'NOT APPLICABLE','I',
                   'ADULT'])]

In [22]:
df.shape

(30267, 148)

In [23]:
df.isnull().sum(axis=1).sort_values(ascending=False)

3864     124
4408     124
4334     124
4300     124
4246     124
4211     124
4175     124
4140     124
4104     124
4082     124
4045     124
4029     124
3996     124
3963     124
3932     124
3900     124
3809     124
3770     124
3737     124
3709     124
3679     124
3658     124
3630     124
3602     124
3534     124
4364     124
4265     124
4441     124
4508     124
4567     124
        ...
14362     31
15770     31
16561     31
15878     31
16110     31
15877     31
16410     31
16717     31
11056     28
25332     28
16379     26
12523     25
26895     25
14021     24
23675     23
17932     22
11399     20
18796     19
18649     19
25195     19
22039     17
20408     17
23535     17
20259     17
21895     17
17213     17
15526     16
17069     15
14161     14
15673     14
Length: 30267, dtype: int64

In [24]:
#check nans
df.isnull().sum().sort_values(ascending=False)

CLSAVGG12          30108
CLSNUMG12          30097
HSOPCTHSGTOT       28923
HSOPCTSENTOT       28923
HSOPCTDRPTOT       28923
HSOPCTDCHTOT       28885
HPGPERDIP6AVG      28331
HPGG08PROF         28307
HPGPERDIP4AVG      27928
HPGGENREGREMAVG    27804
HPGGEN10CYR3AVG    27795
HPGGEN10CYR2AVG    27708
HPGGEN10CYR1AVG    27638
ENRNUMELL          26998
ENRNUMPOV          26998
ENRNUMOTH          26998
HSOPCTDRPNYC       26033
HSOPCTSENNYC       26033
HSOPCTHSGNYC       26033
CLSAVGGEN          25824
CLSAVGG11          24218
CLSNUMG11          24217
ATTPCTG12          24104
CLSNUMG10          23885
CLSAVGG10          23885
ATTPCTG11          23745
STCELAPCTL34G07    23376
CLSAVGG09          23364
STCMTHPCTL34G08    23363
CLSNUMG09          23362
                   ...
SCHLOGRD            2349
ATTPCTTOT           1844
CLSAVGTOT           1026
CLSNUMTOT           1026
SCHGRDCONFIG         955
SCHNAM               688
BNLONG               636
ENRNUMG08              0
ENRNUMPRK              0
ENRNUMKID              0
ENRNUMG01              0
ENRNUMG02              0
ENRNUMG03              0
ENRNUMG04              0
ENRNUMG05              0
ENRNUMG06              0
ENRNUMG07              0
ENRNUMG10              0
ENRNUMG09              0
YEAR                   0
ENRNUMG11              0
ENRNUMG12              0
ENRNUMOHS              0
ENRNUMSPD              0
ENRNUMTOT              0
CBO                    0
SPECHS                 0
DBN                    0
ENRNUMGEN              0
CTMSCH                 0
Length: 148, dtype: int64

# Question: predicting school closures

In [25]:
df['LCGSTAT'].value_counts(dropna=False)

OPEN      19619
NaN       10624
CLOSED       24
Name: LCGSTAT, dtype: int64

In [26]:
df[df['LCGSTAT'] == 'CLOSED']

,SCHLEV,SCHLEV5,ENRNUMPRK,ENRNUMKID,ENRNUMG01,ENRNUMG02,ENRNUMG03,ENRNUMG04,ENRNUMG05,ENRNUMG06,...,DMGPCTELLTOT,CTMSCH,CBO,SPECHS,DBN,SCHNAM,YEAR,BNLONG,CCDNUMFTE_normd,CCDENRNUMFRL_normd
9872,2.0,2.0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,01M450,EAST SIDE COMMUNITY HIGH SCHOO,2004,M450,0.160377,NaN
9873,2.0,2.0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,01M509,CMSP CHANCELLOR'S MODEL SCHOOL,2004,NaN,0.178417,NaN
9875,1.0,1.0,0,85,63,59,0,0,0,47,...,NaN,0,0,0,01M539,NEST+M,2004,M539,0.147239,NaN
10017,1.0,1.0,6,13,17,45,39,49,47,44,...,NaN,0,0,0,04M109,HOSTOS ACADEMY AT JHS99M,2004,M109,0.030508,NaN
10052,2.0,2.0,0,0,0,0,0,35,54,56,...,NaN,0,0,0,05M469,CHOIR ACADEMY OF HARLEM,2004,M469,0.108614,NaN
10073,1.0,1.0,0,105,94,94,100,97,71,37,...,NaN,0,0,0,06M176,W. HAYWOOD BURNS SCHOOL #176,2004,M176,0.035397,NaN
10101,2.0,2.0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,07X149,ELIJAH D. CLARK - JHS # 149,2004,X149,0.103067,NaN
10131,1.0,1.0,0,102,128,113,116,132,105,0,...,NaN,0,0,0,08X060,GEORGE L. GALLEGO SCHOOL,2004,X060,NaN,NaN
10251,1.0,1.0,0,192,100,0,0,0,0,0,...,NaN,0,0,0,10X257,THE CHILDREN'S SCHOOL,2004,X257,0.080906,NaN
10454,2.0,2.0,0,0,0,0,0,0,0,110,...,NaN,0,0,0,15K142,STRANAHAN IS (RENAMED 378),2004,K142,0.018248,NaN
10464,2.0,2.0,0,0,0,0,0,0,0,60,...,NaN,0,0,0,15K429,THE BROOKLYN SCHOOL FOR GLOBAL,2004,K429,0.172589,NaN
10468,1.0,1.0,0,0,0,0,0,0,0,132,...,NaN,0,0,0,15K448,NaN,2004,K448,0.082742,NaN
10472,2.0,2.0,0,0,0,0,0,0,0,70,...,NaN,0,0,0,15K496,THE SCHOOL FOR INTERNATIONAL S,2004,K496,NaN,NaN
10595,2.0,2.0,0,0,0,0,0,0,0,53,...,NaN,0,0,0,19K409,EAST NEW YORK FAMILY ACADEMY,2004,K409,0.195804,NaN
10663,2.0,2.0,0,0,0,0,0,0,0,76,...,NaN,0,0,0,21K280,BROOKLYN STUDIO SECONDARY SCH.,2004,K280,0.089712,NaN
10734,2.0,2.0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,23K696,TEACHERS PREPARATORY SCHOOL,2004,K696,NaN,NaN
10921,2.0,2.0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,28Q680,QUEENS GATEWAY,2004,Q680,0.158470,NaN
11167,3.0,3.0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,76K460,JOHN JAY HIGH SCHOOL,2004,K460,NaN,NaN
11168,10.0,4.0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,76K497,THE SCHOOL FOR INTERNATIONAL S,2004,K497,NaN,NaN
11173,8.0,4.0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,79K512,BUSHWICK OUTREACH,2004,K512,NaN,NaN
11181,8.0,4.0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,79M502,LOWER MANHATTAN OUTREACH,2004,M502,NaN,NaN
11183,8.0,4.0,0,0,0,0,0,0,0,0,...,NaN,0,0,0,79M530,PROJECT BLEND,2004,M530,NaN,NaN
14812,2.0,2.0,0,0,0,0,0,0,0,0,...,3.703704,0,0,0,14K033,JHS 033 MARK HOPKINS,2007,K033,NaN,NaN
14943,2.0,2.0,0,0,0,0,0,0,0,0,...,3.720930,0,0,0,17K390,M S 390 MAGGIE L. WALKER,2007,K390,0.145116,0.944186

In [108]:
choices = list(df['SCHNAM'].unique())
process.extract("Samuel Tilden", choices, scorer=fuzz.token_sort_ratio)

[('SAMUEL J. TILDEN HIGH SCHOOL', 65),
 ('SAMUEL STERN SCHOOL', 62),
 ('P.S. 007 SAMUEL STERN', 61),
 ('SAMUEL MILLS SPROLE', 56),
 ('THE LAURELTON', 54)]

In [121]:
df[df['BNLONG'] == 'M450']

,DBN,SCHNAM,YEAR,SCHLEV,SCHLEV5,SCHS219962016,XDBN,XDBN_FLAG,ENRNUMPRK,ENRNUMKID,...,BNLONG_TOTALYRS,BNLONG_PHASEDOUT19962016,BNLONG_PHASEDIN19962016,BNLONG_CONTOPERATE19962016,CBO,HSJHS,HSSCHSAMP2,SPECHS,CCDNUMFTE_normd,CCDENRNUMFRL_normd
21,01M450,EAST SIDE COMMUNITY HIGH SCHOO,1996,NaN,NaN,NaN,01M450,0,0,0,...,21.0,0,0,0,0,NaN,6,0,NaN,NaN
1175,01M450,EAST SIDE COMMUNITY HIGH SCHOO,1997,NaN,NaN,NaN,01M450,0,0,0,...,21.0,0,0,0,0,NaN,6,0,NaN,NaN
2346,01M450,EAST SIDE COMMUNITY HIGH SCHOO,1998,NaN,NaN,NaN,01M450,0,0,0,...,21.0,0,0,0,0,NaN,6,0,NaN,NaN
3530,01M450,EAST SIDE COMMUNITY HIGH SCHOO,1999,NaN,NaN,NaN,01M450,0,0,0,...,21.0,0,0,0,0,NaN,6,0,NaN,NaN
4752,01M450,EAST SIDE COMMUNITY HIGH SCHOO,2000,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,NaN,7,0,NaN,NaN
6018,01M450,EAST SIDE COMMUNITY HIGH SCHOO,2001,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,NaN,7,0,NaN,NaN
7290,01M450,EAST SIDE COMMUNITY HIGH SCHOO,2002,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,NaN,7,0,NaN,NaN
8568,01M450,EAST SIDE COMMUNITY HIGH SCHOO,2003,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,NaN,7,0,NaN,NaN
9872,01M450,EAST SIDE COMMUNITY HIGH SCHOO,2004,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,NaN,7,0,0.160377,NaN
11228,01M450,EAST SIDE COMMUNITY HIGH SCHOO,2005,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,0.0,1,0,0.066798,0.000000
12675,01M450,EAST SIDE COMMUNITY HIGH SCHOO,2006,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,0.0,1,0,0.067864,0.796407
14158,01M450,EAST SIDE COMMUNITY SCHOOL,2007,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,0.0,1,0,0.074199,0.709964
15670,01M450,EAST SIDE COMMUNITY SCHOOL,2008,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,0.0,1,0,0.076173,0.788809
17210,01M450,EAST SIDE COMMUNITY SCHOOL,2009,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,0.0,1,0,0.076740,0.793040
18793,01M450,EAST SIDE COMMUNITY SCHOOL,2010,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,0.0,1,0,0.076208,NaN
20404,01M450,EAST SIDE COMMUNITY SCHOOL,2011,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,0.0,1,0,0.072037,0.816361
22035,01M450,EAST SIDE COMMUNITY SCHOOL,2012,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,0.0,1,0,0.076003,0.792642
23671,01M450,EAST SIDE COMMUNITY SCHOOL,2013,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,0.0,1,0,NaN,NaN
25328,01M450,EAST SIDE COMMUNITY SCHOOL,2014,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,0.0,1,0,NaN,NaN
27029,01M450,EAST SIDE COMMUNITY SCHOOL,2015,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,0.0,1,0,NaN,NaN
28697,01M450,EAST SIDE COMMUNITY SCHOOL,2016,2.0,2.0,1.0,01M450,0,0,0,...,21.0,0,0,0,0,0.0,1,0,NaN,NaN

In [28]:
dff = pd.melt(df, id_vars=['BNLONG', 'YEAR'])#.pivot(index='BNLONG', columns='YEAR')

In [30]:
dff.head()

  BNLONG  YEAR variable value
0   M801  1996   SCHLEV   NaN
1   M802  1996   SCHLEV   NaN
2   M803  1996   SCHLEV   NaN
3   M015  1996   SCHLEV   NaN
4   M019  1996   SCHLEV   NaN

In [34]:
f1 = dff.groupby(["BNLONG",'variable', "YEAR"])['value'].aggregate(lambda x: x).unstack().reset_index()
f1.columns=f1.columns.tolist()

In [37]:
f1.shape

(291416, 23)

In [43]:
f1 = f1[~(f1.isnull().sum(axis=1) >= 21)]

In [44]:
f1

,BNLONG,variable,1996,1997,1998,1999,2000,2001,2002,2003,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,K001,ATTPCTG01,88.76,92.53,90.76,91.04,91.62,91.57,91.88,92.76,...,93.98,93.56,94.45,93.49,93,94.86,94.81,93.87,95.12,95.62
1,K001,ATTPCTG02,91.33,91.37,92.66,92,92.26,93.87,92.71,93.02,...,93.16,94.99,94.87,95.46,93.83,94.68,94.86,95.12,95.38,95.55
2,K001,ATTPCTG03,92.43,93.11,92.36,93.55,92.9,92.77,94.14,93.56,...,94.57,94.37,95.75,95.55,95.14,95.57,95.35,95.26,95.74,96.32
3,K001,ATTPCTG04,92.36,93.75,92.44,91.88,93.99,93.17,92.38,94.3,...,94,94.81,93.66,95.5,95.65,96.35,95.85,95.16,95.67,96.5
4,K001,ATTPCTG05,93.04,92.92,92.61,93.2,92.07,94.12,93.25,93.45,...,94.02,94.43,95.38,94.12,95.74,95.81,96.4,94.99,95.64,95.79
12,K001,ATTPCTKID,89.73,90.98,89.44,89.96,90.36,90.46,89.16,92.66,...,92.31,93.87,92.95,92.44,93.14,94.34,93.55,93.67,94.51,93.65
13,K001,ATTPCTPRK,79.9,86.19,87.09,84.75,85.54,81.24,86.81,89.33,...,88.92,90.42,89.73,91.65,89.24,92.8,91.95,91.58,90.89,93.79
14,K001,ATTPCTTOT,90.36,91.97,91.28,91.39,91.57,91.65,91.88,92.78,...,92.94,93.68,93.82,94.06,93.68,94.9,94.67,94.25,94.84,95.32
15,K001,CBO,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
20,K001,CLSAVGG01,25.5385,30,27,30.1429,24.8,18.6364,21.3,19.1111,...,20.8,20.1333,22.6667,19.2941,21.4667,26,34.3077,34.3077,24,25.1429
21,K001,CLSAVGG02,30.5455,27,29,26.2857,33.2857,23,21.2222,22.125,...,21.0667,19.0667,19.8667,24.9333,21.4667,22.6154,26.6154,38,30.9231,26.1429
22,K001,CLSAVGG03,28.4444,35.5556,26.9091,33.8,30.1667,32.5,26.8571,22,...,25.2727,28,24.7273,25.4545,31.6364,23.8333,27.2,27.0909,28,32.2
23,K001,CLSAVGG04,32,27.7778,30.6667,22.4,40.75,28.3333,29,30.3333,...,21.3333,21.5,27.0909,25.0909,24.3636,33.4,22.5,26.2,36.5,31
32,K001,CLSAVGGEN,30.5806,31.6129,30.5588,29.0833,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,K001,CLSAVGKID,27,26,27.8571,19.875,15.8462,17.6364,17.1818,23.7143,...,18.8,20.4,19.6,24.1538,23.2,32.1538,26.8,22.4211,23.4667,27
34,K001,CLSAVGOHS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
35,K001,CLSAVGPRK,17.75,18,18,18.75,18,18.1667,18,16.8889,...,16.8889,15.6364,15.6667,15.8889,15.8889,14.3,15.8889,15.625,15.625,15
36,K001,CLSAVGSPD,12.5,12.75,13,12.5,9,11,11.3333,8.33333,...,22.6667,27.6667,31.3333,32,28.25,25.25,27.25,29,23.3333,42
37,K001,CLSAVGTOT,28.5143,29.4571,29.5833,28.2105,26.125,24.6154,24.26,24.2245,...,22.2268,22.0792,22.866,24.0825,24.202,25.4316,27.0737,27.4624,24.7843,26.2653
38,K001,CLSNUMG01,6.5,6,7,7,10,11,10,9,...,7.5,7.5,7.5,8.5,7.5,6.5,6.5,6.5,8,7
39,K001,CLSNUMG02,5.5,6,6,7,7,10,9,8,...,7.5,7.5,7.5,7.5,7.5,6.5,6.5,5,6.5,7
40,K001,CLSNUMG03,4.5,4.5,5.5,5,6,6,7,7,...,5.5,5.5,5.5,5.5,5.5,6,5,5.5,6,5
41,K001,CLSNUMG04,4.5,4.5,4.5,5,4,6,6,6,...,6,6,5.5,5.5,5.5,5,6,5,4,5
50,K001,CLSNUMGEN,31,31,34,36,46,50,47,46,...,45.5,47.5,45.5,45.5,45.5,43.5,43.5,42.5,45,45
51,K001,CLSNUMKID,6,6,7,8,13,11,11,7,...,7.5,7.5,7.5,6.5,7.5,6.5,7.5,9.5,7.5,7
52,K001,CLSNUMOHS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.5,2.5,3,3,3,3,3,3,5,6
53,K001,CLSNUMPRK,4,4,4,4,6,6,4,9,...,9,11,9,9,9,10,9,8,8,8
54,K001,CLSNUMSPD,4,4,2,2,2,2,3,3,...,3,3,3,3,4,4,4,4,6,4
55,K001,CLSNUMTOT,35,35,36,38,48,52,50,49,...,48.5,50.5,48.5,48.5,49.5,47.5,47.5,46.5,51,49
56,K001,CTMSCH,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291331,X966,ENRNUMASI,None,None,None,None,None,None,None,None,...,None,None,None,1,1,None,None,None,None,None
291333,X966,ENRNUMFEM,None,None,None,None,None,None,None,None,...,None,None,None,4,8,None,None,None,None,None
291334,X966,ENRNUMG01,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None
291335,X966,ENRNUMG02,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None
291336,X966,ENRNUMG03,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None
291337,X966,ENRNUMG04,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None
291338,X966,ENRNUMG05,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None
291339,X966,ENRNUMG06,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None
291340,X966,ENRNUMG07,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None
291341,X966,ENRNUMG08,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None
291342,X966,ENRNUMG09,None,None,None,None,None,None,None,None,...,None,None,None,8,14,None,None,None,None,None
291343,X966,ENRNUMG10,None,None,None,None,None,None,None,None,...,None,None,None,8,7,None,None,None,None,None
291344,X966,ENRNUMG11,None,None,None,None,None,None,None,None,...,None,None,None,2,3,None,None,None,None,None
291345,X966,ENRNUMG12,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None
291346,X966,ENRNUMGEN,None,None,None,None,None,None,None,None,...,None,None,None,18,24,None,None,None,None,None
291347,X966,ENRNUMHIS,None,None,None,None,None,None,None,None,...,None,None,None,6,17,None,None,None,None,None
291348,X966,ENRNUMKID,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None
291349,X966,ENRNUMMAL,None,None,None,None,None,None,None,None,...,None,None,None,17,19,None,None,None,None,None
291350,X966,ENRNUMOHS,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None
291353,X966,ENRNUMPRK,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None
291354,X966,ENRNUMSPD,None,None,None,None,None,None,None,None,...,None,None,None,3,3,None,None,None,None,None
291355,X966,ENRNUMTOT,None,None,None,None,None,None,None,None,...,None,None,None,21,27,None,None,None,None,None
291356,X966,ENRNUMWHT,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None
291395,X966,SCHGRDCONFIG,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None
291396,X966,SCHHIGRD,None,None,None,None,None,None,None,None,...,None,None,None,NaN,9,None,None,None,None,None
291397,X966,SCHLEV,None,None,None,None,None,None,None,None,...,None,None,None,8,8,None,None,None,None,None
291398,X966,SCHLEV5,None,None,None,None,None,None,None,None,...,None,None,None,4,4,None,None,None,None,None
291399,X966,SCHLOGRD,None,None,None,None,None,None,None,None,...,None,None,None,NaN,9,None,None,None,None,None
291400,X966,SCHNAM,None,None,None,None,None,None,None,None,...,None,None,None,SUSPENSION CENTER SCHOOL AYA,SUSPENSION CENTER SCHOOL AYA,None,None,None,None,None
291401,X966,SPECHS,None,None,None,None,None,None,None,None,...,None,None,None,0,0,None,None,None,None,None